set MQSI_SHOW_DEPLOY=1
set MQSI_DEPLOY_PROGRESS=1
set MQSIJVERBOSE=-DMQSI_CONSOLEMODE=2
set MQSI_FORCE_DEBUG_TRACING=true
set MQSI_FORCE_TRACE_SIZE=9999999
set MQSI_RUN_ATTACHED=1
set MQSI_DISABLE_CVP=1
set MQSI_SOAP_DEBUG=1