--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "IIBADMIN"."DEPARTMENT" DROP CONSTRAINT "RDE";

ALTER TABLE "IIBADMIN"."DEPARTMENT" DROP CONSTRAINT "ROD";

ALTER TABLE "IIBADMIN"."DEPARTMENT" DROP CONSTRAINT "PK_DEPARTMENT";

DROP INDEX "IIBADMIN"."XDEPT2";

DROP INDEX "IIBADMIN"."XDEPT3";

DROP TABLE "IIBADMIN"."DEPARTMENT";

CREATE TABLE "IIBADMIN"."DEPARTMENT" (
		"DEPTNO" CHAR(3) NOT NULL,
		"DEPTNAME" VARCHAR(36) NOT NULL,
		"MGRNO" CHAR(6),
		"ADMRDEPT" CHAR(3) NOT NULL,
		"LOCATION" CHAR(16)
	)
	DATA CAPTURE NONE;

CREATE INDEX "IIBADMIN"."XDEPT2"
	ON "IIBADMIN"."DEPARTMENT"
	("MGRNO"		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE INDEX "IIBADMIN"."XDEPT3"
	ON "IIBADMIN"."DEPARTMENT"
	("ADMRDEPT"		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

ALTER TABLE "IIBADMIN"."DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY
	("DEPTNO");

ALTER TABLE "IIBADMIN"."DEPARTMENT" ADD CONSTRAINT "RDE" FOREIGN KEY
	("MGRNO")
	REFERENCES "IIBADMIN"."EMPLOYEE"
	("EMPNO")
	ON DELETE SET NULL;

ALTER TABLE "IIBADMIN"."DEPARTMENT" ADD CONSTRAINT "ROD" FOREIGN KEY
	("ADMRDEPT")
	REFERENCES "IIBADMIN"."DEPARTMENT"
	("DEPTNO")
	ON DELETE CASCADE;

