--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "IIBADMIN"."EMPLOYEE" DROP CONSTRAINT "RED";

ALTER TABLE "IIBADMIN"."EMPLOYEE" DROP CONSTRAINT "NUMBER";

ALTER TABLE "IIBADMIN"."EMPLOYEE" DROP CONSTRAINT "PK_EMPLOYEE";

DROP INDEX "IIBADMIN"."XEMP2";

DROP TABLE "IIBADMIN"."EMPLOYEE";

CREATE TABLE "IIBADMIN"."EMPLOYEE" (
		"EMPNO" CHAR(6) NOT NULL,
		"FIRSTNME" VARCHAR(12) NOT NULL,
		"MIDINIT" CHAR(1),
		"LASTNAME" VARCHAR(15) NOT NULL,
		"WORKDEPT" CHAR(3),
		"PHONENO" CHAR(4),
		"HIREDATE" DATE,
		"JOB" CHAR(8),
		"EDLEVEL" SMALLINT NOT NULL,
		"SEX" CHAR(1),
		"BIRTHDATE" DATE,
		"SALARY" DECIMAL(9 , 2),
		"BONUS" DECIMAL(9 , 2),
		"COMM" DECIMAL(9 , 2)
	)
	DATA CAPTURE NONE;

CREATE INDEX "IIBADMIN"."XEMP2"
	ON "IIBADMIN"."EMPLOYEE"
	("WORKDEPT"		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

ALTER TABLE "IIBADMIN"."EMPLOYEE" ADD CONSTRAINT "NUMBER" CHECK (PHONENO >= '0000' AND PHONENO <= '9999');

ALTER TABLE "IIBADMIN"."EMPLOYEE" ADD CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY
	("EMPNO");

ALTER TABLE "IIBADMIN"."EMPLOYEE" ADD CONSTRAINT "RED" FOREIGN KEY
	("WORKDEPT")
	REFERENCES "IIBADMIN"."DEPARTMENT"
	("DEPTNO")
	ON DELETE SET NULL;

